name: whiteboard

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - int_network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: app_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - int_network

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local

networks:
  int_network:
    driver: bridge
